import { 
  Profile, 
  HeroData, 
  Skill, 
  Project, 
  Certification, 
  Education, 
  Experience, 
  Research, 
  NavigationItem, 
  SiteSettings, 
  DocumentItem,
  ContactMessage
} from '../types';

export const initialProfile: Profile = {
  id: '00000000-0000-0000-0000-000000000001',
  full_name: 'Jhampier Iván Juárez Mauricio',
  headline: 'Egresado de Ingeniería de Sistemas | Software Developer | IA',
  bio_short: 'Soy egresado de Ingeniería de Sistemas con formación en análisis, diseño y desarrollo de software.',
  bio_long: 'Egresado de Ingeniería de Sistemas con enfoque principal en el desarrollo Full Stack, desarrollo web moderno, inteligencia artificial y automatización. Orientado a resolver problemas mediante tecnología, integración de APIs, bases de datos robustas, IoT y diseño de redes. Actualmente en búsqueda activa de oportunidades profesionales como Software Developer / Full Stack Developer, preferentemente en modalidad remota.',
  location: 'Piura, Perú',
  email: 'jhampier.juarez@example.com',
  github_url: 'https://github.com/breakscode',
  linkedin_url: '',
  avatar_url: '',
  status_text: 'Disponible para oportunidades como Software Developer / Full Stack Developer',
};

export const initialHero: HeroData = {
  id: '00000000-0000-0000-0000-000000000002',
  greeting: 'Hola, soy Jhampier',
  role_title: 'Software Developer',
  subtitle: 'Construyo soluciones web, sistemas inteligentes y experiencias digitales.',
  cta_primary_text: 'Ver proyectos',
  cta_primary_link: '#projects',
  cta_secondary_text: 'Descargar CV',
  cta_secondary_link: '#cv',
  cta_tertiary_text: 'Contactarme',
  cta_tertiary_link: '#contact',
  tech_badge: 'Full Stack & AI Focused',
  is_active: true,
};

export const initialSkills: Skill[] = [
  // Frontend
  { id: 'sk-1', name: 'React', category: 'frontend', icon_name: 'Code2', highlight: true, is_published: true, sort_order: 1 },
  { id: 'sk-2', name: 'React 19', category: 'frontend', icon_name: 'Sparkles', highlight: true, is_published: true, sort_order: 2 },
  { id: 'sk-3', name: 'TypeScript', category: 'frontend', icon_name: 'FileCode', highlight: true, is_published: true, sort_order: 3 },
  { id: 'sk-4', name: 'JavaScript', category: 'frontend', icon_name: 'FileCode', highlight: false, is_published: true, sort_order: 4 },
  { id: 'sk-5', name: 'Tailwind CSS', category: 'frontend', icon_name: 'Palette', highlight: true, is_published: true, sort_order: 5 },
  { id: 'sk-6', name: 'Vite', category: 'frontend', icon_name: 'Zap', highlight: false, is_published: true, sort_order: 6 },
  { id: 'sk-7', name: 'React Router', category: 'frontend', icon_name: 'Compass', highlight: false, is_published: true, sort_order: 7 },
  { id: 'sk-8', name: 'React Hook Form', category: 'frontend', icon_name: 'CheckSquare', highlight: false, is_published: true, sort_order: 8 },
  { id: 'sk-9', name: 'Zod', category: 'frontend', icon_name: 'ShieldCheck', highlight: false, is_published: true, sort_order: 9 },
  { id: 'sk-10', name: 'Recharts', category: 'frontend', icon_name: 'BarChart2', highlight: false, is_published: true, sort_order: 10 },
  { id: 'sk-11', name: 'HTML5', category: 'frontend', icon_name: 'Layout', highlight: false, is_published: true, sort_order: 11 },
  { id: 'sk-12', name: 'CSS3', category: 'frontend', icon_name: 'Layers', highlight: false, is_published: true, sort_order: 12 },

  // Backend
  { id: 'sk-13', name: 'Node.js', category: 'backend', icon_name: 'Server', highlight: true, is_published: true, sort_order: 1 },
  { id: 'sk-14', name: 'NestJS', category: 'backend', icon_name: 'Cpu', highlight: true, is_published: true, sort_order: 2 },
  { id: 'sk-15', name: 'PHP', category: 'backend', icon_name: 'Code', highlight: false, is_published: true, sort_order: 3 },
  { id: 'sk-16', name: 'Java', category: 'backend', icon_name: 'Coffee', highlight: false, is_published: true, sort_order: 4 },
  { id: 'sk-17', name: 'REST APIs', category: 'backend', icon_name: 'Globe', highlight: true, is_published: true, sort_order: 5 },
  { id: 'sk-18', name: 'JWT', category: 'backend', icon_name: 'Key', highlight: false, is_published: true, sort_order: 6 },
  { id: 'sk-19', name: 'Bcrypt', category: 'backend', icon_name: 'Lock', highlight: false, is_published: true, sort_order: 7 },

  // Databases
  { id: 'sk-20', name: 'PostgreSQL', category: 'database', icon_name: 'Database', highlight: true, is_published: true, sort_order: 1 },
  { id: 'sk-21', name: 'Supabase', category: 'database', icon_name: 'Flame', highlight: true, is_published: true, sort_order: 2 },
  { id: 'sk-22', name: 'Prisma ORM', category: 'database', icon_name: 'Boxes', highlight: true, is_published: true, sort_order: 3 },
  { id: 'sk-23', name: 'Redis', category: 'database', icon_name: 'Zap', highlight: false, is_published: true, sort_order: 4 },
  { id: 'sk-24', name: 'MySQL', category: 'database', icon_name: 'Database', highlight: false, is_published: true, sort_order: 5 },
  { id: 'sk-25', name: 'SQL Server', category: 'database', icon_name: 'Server', highlight: false, is_published: true, sort_order: 6 },
  { id: 'sk-26', name: 'SQLite', category: 'database', icon_name: 'HardDrive', highlight: false, is_published: true, sort_order: 7 },

  // AI & Automation
  { id: 'sk-27', name: 'Google Gemini', category: 'ai_automation', icon_name: 'Bot', highlight: true, is_published: true, sort_order: 1 },
  { id: 'sk-28', name: 'n8n', category: 'ai_automation', icon_name: 'Workflow', highlight: true, is_published: true, sort_order: 2 },
  { id: 'sk-29', name: 'TensorFlow', category: 'ai_automation', icon_name: 'Binary', highlight: true, is_published: true, sort_order: 3 },
  { id: 'sk-30', name: 'Inteligencia Artificial', category: 'ai_automation', icon_name: 'Brain', highlight: true, is_published: true, sort_order: 4 },
  { id: 'sk-31', name: 'Automatización', category: 'ai_automation', icon_name: 'Cog', highlight: true, is_published: true, sort_order: 5 },
  { id: 'sk-32', name: 'MCP', category: 'ai_automation', icon_name: 'Network', highlight: false, is_published: true, sort_order: 6 },

  // Tools
  { id: 'sk-33', name: 'Git', category: 'tools', icon_name: 'GitBranch', highlight: true, is_published: true, sort_order: 1 },
  { id: 'sk-34', name: 'GitHub', category: 'tools', icon_name: 'Github', highlight: true, is_published: true, sort_order: 2 },
  { id: 'sk-35', name: 'Vercel', category: 'tools', icon_name: 'UploadCloud', highlight: false, is_published: true, sort_order: 3 },

  // Other
  { id: 'sk-36', name: 'Power BI', category: 'other', icon_name: 'PieChart', highlight: false, is_published: true, sort_order: 1 },
  { id: 'sk-37', name: 'LAN', category: 'other', icon_name: 'Network', highlight: false, is_published: true, sort_order: 2 },
  { id: 'sk-38', name: 'VLAN', category: 'other', icon_name: 'Share2', highlight: false, is_published: true, sort_order: 3 },
  { id: 'sk-39', name: 'DHCP', category: 'other', icon_name: 'Wifi', highlight: false, is_published: true, sort_order: 4 },
  { id: 'sk-40', name: 'IoT', category: 'other', icon_name: 'Radio', highlight: true, is_published: true, sort_order: 5 },
];

export const initialProjects: Project[] = [
  {
    id: 'proj-1',
    title: 'Sistema Integral de Gestión Patrimonial',
    slug: 'sistema-gestion-patrimonial',
    short_description: 'Sistema web orientado a la gestión y control del inventario y patrimonio institucional.',
    full_description: 'Plataforma integral diseñada para centralizar el registro, categorización, asignación, depreciación y auditoría de bienes patrimoniales institucionales con integración de análisis asistido por IA.',
    problem_statement: 'La institución enfrentaba retrasos y riesgos de inconsistencia al manejar registros manuales y dispersos del inventario patrimonial.',
    solution_statement: 'Desarrollo de un sistema web reactivo y seguro con backend en Supabase/PostgreSQL, visualización de métricas en Recharts e integración con Gemini 2.5 Flash para asistencia analítica.',
    results_statement: 'Centralización del 100% de los bienes institucionales con trazabilidad completa y generación automatizada de reportes.',
    year: '2026',
    organization: 'IESTP Juan José Farfán',
    location: 'Sullana, Piura',
    category: 'Full Stack',
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Supabase', 'PostgreSQL', 'Gemini 2.5 Flash', 'Recharts'],
    main_image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80'
    ],
    github_url: '',
    demo_url: '',
    status: 'Completado',
    is_featured: true,
    is_published: true,
    sort_order: 1,
  },
  {
    id: 'proj-2',
    title: 'Sistema Web para Optimización de Ventas',
    slug: 'sistema-optimizacion-ventas',
    short_description: 'Sistema web desarrollado para optimizar procesos relacionados con ventas y gestión de información.',
    full_description: 'Arquitectura Full Stack orientada a la agilización de ventas, control de inventario en tiempo real y autenticación segura con roles.',
    problem_statement: 'Necesidad de optimizar los tiempos de atención en ventas y consolidar la información transaccional con baja latencia.',
    solution_statement: 'Implementación de una arquitectura modular basada en React en frontend y NestJS en backend con Prisma ORM, caché en Redis y persistencia en PostgreSQL.',
    results_statement: 'Flujo de ventas optimizado y consultas de stock en tiempo real protegidas mediante tokens JWT.',
    year: '2025',
    organization: 'Comercial Rafael Norte S.A.C.',
    location: 'Piura',
    category: 'Full Stack',
    technologies: ['React', 'NestJS', 'Prisma', 'JWT', 'Redis', 'PostgreSQL'],
    main_image_url: 'https://images.unsplash.com/photo-1556742049-0a67e5572263?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1556742049-0a67e5572263?auto=format&fit=crop&w=1200&q=80'
    ],
    github_url: '',
    demo_url: '',
    status: 'Completado',
    is_featured: true,
    is_published: true,
    sort_order: 2,
  },
  {
    id: 'proj-3',
    title: 'Asistente Inteligente para Consultas y Agendas',
    slug: 'asistente-inteligente-consultas-agendas',
    short_description: 'Proyecto de investigación orientado a automatizar consultas y coordinación de agendas mediante IA y automatización.',
    full_description: 'Solución de automatización inteligente desarrollada como proyecto de investigación titulada: "Automatización de consultas y agendas mediante asistente inteligente usando inteligencia artificial para una institución educativa, Piura 2026".',
    problem_statement: 'Sobrecarga en la atención de consultas frecuentes de estudiantes y dificultades en la coordinación fluida de agendas institucionales.',
    solution_statement: 'Flujos automatizados creados con n8n orquestados con el modelo Google Gemini para comprender el contexto de las solicitudes y gestionar disponibilidad de horarios de manera desatendida.',
    results_statement: 'Automatización de respuestas inmediatas 24/7 y sincronización de citas sin fricción.',
    year: '2026',
    organization: 'Institución Educativa',
    location: 'Piura',
    category: 'IA / Automatización',
    technologies: ['n8n', 'Google Gemini', 'Inteligencia Artificial', 'Automatización'],
    main_image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [],
    github_url: '',
    demo_url: '',
    status: 'Investigación',
    is_featured: true,
    is_published: true,
    sort_order: 3,
  },
  {
    id: 'proj-4',
    title: 'Sistema Inteligente de Categorización de Artículos',
    slug: 'sistema-categorizacion-articulos',
    short_description: 'Sistema orientado a la categorización inteligente de artículos utilizando técnicas de inteligencia artificial.',
    full_description: 'Desarrollo y entrenamiento de un modelo neuronal con TensorFlow y Python para clasificación automatizada de prendas y artículos con alto índice de exactitud.',
    problem_statement: 'Proceso manual y lento de clasificación de artículos susceptibles a errores humanos en la catalogación.',
    solution_statement: 'Diseño de una red neuronal profunda con preprocesamiento de datos y ajuste de hiperparámetros con TensorFlow.',
    results_statement: 'Obtención de un 80.34% de precisión en la categorización del conjunto de prueba.',
    year: '2024',
    organization: '',
    location: 'Piura',
    category: 'IA',
    technologies: ['Python', 'TensorFlow', 'Inteligencia Artificial'],
    main_image_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [],
    github_url: '',
    demo_url: '',
    status: 'Completado',
    is_featured: false,
    is_published: true,
    sort_order: 4,
  },
  {
    id: 'proj-5',
    title: 'Plataforma Integral para Seguimiento del Rendimiento Académico y Conductual',
    slug: 'plataforma-seguimiento-academico-conductual',
    short_description: 'Plataforma web orientada al seguimiento y gestión de información relacionada con el rendimiento académico y conductual.',
    full_description: 'Sistema de gestión escolar para docentes, tutores y directivos enfocado en el registro oportuno de calificaciones, asistencias e incidentes conductuales.',
    problem_statement: 'Dificultad de los docentes para mantener un registro histórico unificado y comunicar oportunamente el estado conductual a directivos.',
    solution_statement: 'Plataforma web modular que centraliza fichas de seguimiento, reportes consolidados y métricas por periodo escolar.',
    results_statement: 'Mejora en el monitoreo preventivo de incidentes escolares y centralización de la información evaluativa.',
    year: '2024',
    organization: 'I.E.P. Los Clavelitos',
    location: 'Piura',
    category: 'Full Stack',
    technologies: ['React', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    main_image_url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [],
    github_url: '',
    demo_url: '',
    status: 'Completado',
    is_featured: false,
    is_published: true,
    sort_order: 5,
  },
  {
    id: 'proj-6',
    title: 'SmartBin IoT',
    slug: 'smartbin-iot',
    short_description: 'Proyecto relacionado con Internet of Things y gestión inteligente de residuos.',
    full_description: 'Prototipo IoT para la detección de nivel de llenado de contenedores de residuos y transmisión de datos a panel centralizado.',
    problem_statement: 'Recolección ineficiente de residuos por rutas fijas sin conocimiento previo del estado de los contenedores.',
    solution_statement: 'Integración de microcontroladores con sensores de proximidad y módulo de comunicación para emitir alertas de nivel crítico.',
    results_statement: 'Demostración funcional de recolección bajo demanda mediante telemetría IoT.',
    year: '2024',
    organization: '',
    location: 'Piura',
    category: 'IoT',
    technologies: ['IoT', 'Sensores', 'Microcontroladores', 'C/C++'],
    main_image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [],
    github_url: '',
    demo_url: '',
    status: 'Completado',
    is_featured: false,
    is_published: true,
    sort_order: 6,
  },
  {
    id: 'proj-7',
    title: 'Rediseño de una Red LAN Estructurada',
    slug: 'rediseno-red-lan-estructurada',
    short_description: 'Proyecto relacionado con diseño y rediseño de infraestructura de red LAN.',
    full_description: 'Diseño y segmentación lógica de infraestructura de red local para mejorar la seguridad, segmentación departamental y rendimiento.',
    problem_statement: 'Congestión por dominios de broadcast amplios y falta de aislamiento entre departamentos organizacionales.',
    solution_statement: 'Segmentación mediante VLANs, configuración de servidores DHCP con direccionamiento eficiente y esquemas de enrutamiento seguros.',
    results_statement: 'Topología de red optimizada, tráfico segmentado y control de accesos por subred.',
    year: '2025',
    organization: '',
    location: 'Piura',
    category: 'Redes',
    technologies: ['LAN', 'VLAN', 'DHCP', 'Cisco Packet Tracer', 'Routing & Switching'],
    main_image_url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [],
    github_url: '',
    demo_url: '',
    status: 'Completado',
    is_featured: false,
    is_published: true,
    sort_order: 7,
  }
];

export const initialCertifications: Certification[] = [
  { id: 'cert-1', name: 'Claude Certified Architect', issuer: 'Anthropic', issue_date: '2026', description: 'Certificación en arquitectura y diseño de soluciones avanzadas con modelos Claude de Anthropic.', is_published: true, sort_order: 1 },
  { id: 'cert-2', name: 'Claude Code in Action', issuer: 'Anthropic Academy', issue_date: '2026', description: 'Especialización en desarrollo asistido y flujos de trabajo avanzados de codificación con Claude.', is_published: true, sort_order: 2 },
  { id: 'cert-3', name: 'Google AI Essentials', issuer: 'Google', issue_date: '', description: 'Fundamentos de inteligencia artificial, prompts efectivos y aplicaciones en productividad.', is_published: true, sort_order: 3 },
  { id: 'cert-4', name: 'GitHub Foundations', issuer: 'GitHub', issue_date: '', description: 'Dominio de control de versiones, colaboración en GitHub, flujos de trabajo y buenas prácticas.', is_published: true, sort_order: 4 },
  { id: 'cert-5', name: 'CyberOps Associate', issuer: 'Cisco', issue_date: '', description: 'Operaciones y fundamentos de ciberseguridad, monitoreo y respuesta ante incidentes.', is_published: true, sort_order: 5 },
  { id: 'cert-6', name: 'Red Hat System Administration I (RH124)', issuer: 'Red Hat', issue_date: '', description: 'Administración de sistemas Linux Red Hat Enterprise, gestión de usuarios, almacenamiento y servicios.', is_published: true, sort_order: 6 },
  { id: 'cert-7', name: 'SQL Server Fundamentals', issuer: 'Microsoft', issue_date: '', description: 'Administración, consultas T-SQL y modelado de bases de datos relacionales en SQL Server.', is_published: true, sort_order: 7 },
  { id: 'cert-8', name: 'Power BI', issuer: 'Microsoft / Certificación Especializada', issue_date: '', description: 'Modelado de datos DAX, visualización de métricas y construcción de dashboards de inteligencia de negocios.', is_published: true, sort_order: 8 },
  { id: 'cert-9', name: 'CCNAv7', issuer: 'Cisco', issue_date: '', description: 'Fundamentos de redes, enrutamiento, conmutación y seguridad de infraestructura IP.', is_published: true, sort_order: 9 },
  { id: 'cert-10', name: 'IBM SkillsBuild', issuer: 'IBM', issue_date: '', description: 'Habilidades tecnológicas e innovación digital.', is_published: true, sort_order: 10 },
  { id: 'cert-11', name: 'HubSpot Content Marketing', issuer: 'HubSpot Academy', issue_date: '', description: 'Estrategias de contenido digital y optimización de canales de comunicación.', is_published: true, sort_order: 11 },
  { id: 'cert-12', name: 'Certificado de Asistencia al Curso de IA 2026', issuer: 'BIG school', issue_date: '2026', description: 'Actualización en tendencias, modelos de lenguaje y herramientas de inteligencia artificial aplicada.', is_published: true, sort_order: 12 },
];

export const initialEducation: Education[] = [
  {
    id: 'edu-1',
    institution: 'Universidad César Vallejo',
    degree: 'Ingeniería de Sistemas',
    field_of_study: 'Análisis, diseño, arquitectura de software, bases de datos, redes e inteligencia artificial',
    period: '2020 — 2026',
    status: 'Egresado',
    location: 'Piura, Perú',
    description: 'Formación académica orientada a la ingeniería de software, gestión de proyectos tecnológicos, desarrollo de sistemas de información, redes y modelos inteligentes.',
    is_published: true,
    sort_order: 1,
  }
];

export const initialExperience: Experience[] = [
  {
    id: 'exp-1',
    type: 'Proyecto profesional',
    organization: 'IESTP Juan José Farfán',
    role_or_title: 'Sistema Integral de Gestión Patrimonial & IA',
    description: 'Desarrollo full stack de sistema web para inventario patrimonial con Supabase, PostgreSQL y análisis automatizado con Gemini 2.5 Flash. Culminación de estudios de Ingeniería de Sistemas.',
    start_date: '2026',
    end_date: '2026',
    year_label: '2026',
    location: 'Sullana, Piura',
    modality: 'Híbrido',
    technologies: ['React', 'TypeScript', 'Supabase', 'PostgreSQL', 'Gemini 2.5 Flash', 'Tailwind CSS'],
    is_published: true,
    sort_order: 1,
  },
  {
    id: 'exp-2',
    type: 'Proyecto académico',
    organization: 'Institución Educativa',
    role_or_title: 'Automatización con IA y n8n',
    description: 'Investigación y desarrollo de asistente inteligente para automatización de consultas y gestión de agendas académicas.',
    start_date: '2026',
    end_date: '2026',
    year_label: '2026',
    location: 'Piura, Perú',
    modality: 'Remoto',
    technologies: ['n8n', 'Google Gemini', 'Inteligencia Artificial', 'Automatización'],
    is_published: true,
    sort_order: 2,
  },
  {
    id: 'exp-3',
    type: 'Proyecto profesional',
    organization: 'Comercial Rafael Norte S.A.C.',
    role_or_title: 'Sistema Web para Optimización de Ventas',
    description: 'Desarrollo de plataforma web para agilización de ventas y control de stock con React, NestJS, Prisma ORM, Redis y PostgreSQL.',
    start_date: '2025',
    end_date: '2025',
    year_label: '2025',
    location: 'Piura',
    modality: 'Remoto',
    technologies: ['React', 'NestJS', 'Prisma', 'Redis', 'PostgreSQL', 'JWT'],
    is_published: true,
    sort_order: 3,
  },
  {
    id: 'exp-4',
    type: 'Proyecto académico',
    organization: '',
    role_or_title: 'Rediseño e Infraestructura de Red LAN',
    description: 'Segmentación de red corporativa con VLANs, esquemas de direccionamiento dinámico DHCP y directivas de seguridad.',
    start_date: '2025',
    end_date: '2025',
    year_label: '2025',
    location: 'Piura',
    modality: 'Presencial',
    technologies: ['LAN', 'VLAN', 'DHCP', 'Cisco Packet Tracer'],
    is_published: true,
    sort_order: 4,
  },
  {
    id: 'exp-5',
    type: 'Proyecto profesional',
    organization: 'I.E.P. Los Clavelitos',
    role_or_title: 'Plataforma de Rendimiento Académico y Conductual',
    description: 'Diseño y desarrollo de sistema web para seguimiento de rendimiento escolar y registro conductual de estudiantes.',
    start_date: '2024',
    end_date: '2024',
    year_label: '2024',
    location: 'Piura',
    modality: 'Híbrido',
    technologies: ['React', 'Node.js', 'PostgreSQL'],
    is_published: true,
    sort_order: 5,
  },
  {
    id: 'exp-6',
    type: 'Proyecto académico',
    organization: '',
    role_or_title: 'Investigación en Clasificación Inteligente con TensorFlow',
    description: 'Entrenamiento de modelo de visión / categorización de prendas obteniendo 80.34% de precisión en el set de validación.',
    start_date: '2024',
    end_date: '2024',
    year_label: '2024',
    location: 'Piura',
    modality: 'Remoto',
    technologies: ['Python', 'TensorFlow', 'Inteligencia Artificial'],
    is_published: true,
    sort_order: 6,
  }
];

export const initialResearch: Research[] = [
  {
    id: 'res-1',
    title: 'Automatización de consultas y agendas mediante asistente inteligente usando inteligencia artificial para una institución educativa, Piura 2026',
    description: 'Proyecto de investigación enfocado en la implementación de agentes inteligentes y flujos autónomos con n8n y Google Gemini para atender consultas estudiantiles e interconectar agendas institucionales de manera reactiva.',
    organization_or_context: 'Proyecto de Investigación Institucional',
    year: '2026',
    technologies: ['n8n', 'Google Gemini', 'Inteligencia Artificial', 'Automatización'],
    key_metric: '24/7',
    metric_label: 'Disponibilidad automatizada de atención',
    is_published: true,
    sort_order: 1,
  },
  {
    id: 'res-2',
    title: 'Sistema Inteligente de Categorización de Artículos mediante Redes Neuronales',
    description: 'Investigación aplicada al procesamiento y clasificación de artículos y prendas mediante técnicas de Deep Learning con TensorFlow, logrando un porcentaje representativo de exactitud experimental.',
    organization_or_context: 'Investigación Aplicada en IA',
    year: '2024',
    technologies: ['Python', 'TensorFlow', 'Deep Learning', 'Computer Vision'],
    key_metric: '80.34%',
    metric_label: 'Precisión lograda en el modelo experimental',
    is_published: true,
    sort_order: 2,
  }
];

export const initialNavigation: NavigationItem[] = [
  { id: 'nav-1', section_id: 'hero', label: 'Inicio', href: '#hero', is_visible: true, sort_order: 1 },
  { id: 'nav-2', section_id: 'about', label: 'Sobre mí', href: '#about', is_visible: true, sort_order: 2 },
  { id: 'nav-3', section_id: 'skills', label: 'Stack', href: '#skills', is_visible: true, sort_order: 3 },
  { id: 'nav-4', section_id: 'projects', label: 'Proyectos', href: '#projects', is_visible: true, sort_order: 4 },
  { id: 'nav-5', section_id: 'experience', label: 'Trayectoria', href: '#experience', is_visible: true, sort_order: 5 },
  { id: 'nav-6', section_id: 'research', label: 'Investigación', href: '#research', is_visible: true, sort_order: 6 },
  { id: 'nav-7', section_id: 'certifications', label: 'Certificaciones', href: '#certifications', is_visible: true, sort_order: 7 },
  { id: 'nav-8', section_id: 'education', label: 'Educación', href: '#education', is_visible: true, sort_order: 8 },
  { id: 'nav-9', section_id: 'contact', label: 'Contacto', href: '#contact', is_visible: true, sort_order: 9 },
];

export const initialSiteSettings: SiteSettings = {
  id: '00000000-0000-0000-0000-000000000010',
  site_name: 'Jhampier Juárez | Software Developer',
  seo_title: 'Jhampier Juárez | Software Developer',
  seo_description: 'Portafolio profesional de Jhampier Juárez, Software Developer especializado en desarrollo Full Stack, inteligencia artificial, automatización y tecnologías web modernas.',
  og_image_url: '',
  favicon_url: '',
  contact_email: 'jhampier.juarez@example.com',
  github_url: 'https://github.com/breakscode',
  linkedin_url: '',
  copyright_text: '© 2026 Jhampier Iván Juárez Mauricio. Todos los derechos reservados.',
  maintenance_mode: false,
};

export const initialDocuments: DocumentItem[] = [
  {
    id: 'doc-1',
    doc_type: 'cv',
    title: 'CV - Jhampier Iván Juárez Mauricio',
    file_url: '#',
    file_name: 'CV_Jhampier_Juarez_Software_Developer.pdf',
    file_size: '245 KB',
    is_active: true,
    updated_at: '2026-02-15T10:00:00Z',
  }
];

export const initialMessages: ContactMessage[] = [
  {
    id: 'msg-1',
    name: 'Tech Recruiter Demo',
    email: 'recruiter@techcompany.com',
    subject: 'Oportunidad Software Developer Full Stack (Remoto)',
    message: 'Hola Jhampier, nos llamó la atención tu perfil y experiencia en React, Supabase y modelos de IA. Nos gustaría coordinar una entrevista preliminar.',
    status: 'new',
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  }
];
